#!/bin/ksh

clear

if [ -f "$HOME/.config/kshrc.once" ]
then
	. "$HOME/.config/kshrc.once"
	rm "$HOME/.config/kshrc.once"
fi

PS1='\W \$ ' 

case $- in
*l*) # Login shell
	if [ "$(tty)" = "/dev/ttyC0" ] && [ -z "$DISPLAY" ]
	then
		XINITRC="$HOME/.config/xinitrc"
		exec startx
	fi
	;;
esac

